<?php
/**
 * Get the version for a given asset.
 *
 * @NOTE
 * - This file is written with a node build script.
 * - Do not edit this file by hand.
 * - See: ./assets/config/asset-versions.js
 *
 * @param string $asset The asset name.
 * @return string The asset version.
 */
function gotham_get_asset_version( $asset ) {
	$assets = array(
		'archive-css' => 'archive.52ef21.css',
		'archive-js' => 'archive.52ef21.js',
		'editor-css' => 'editor.52ef21.css',
		'editor-js' => 'editor.52ef21.js',
		'page-css' => 'page.52ef21.css',
		'page-js' => 'page.52ef21.js',
		'post-css' => 'post.52ef21.css',
		'post-js' => 'post.52ef21.js',
		'site-css' => 'site.52ef21.css',
		'site-js' => 'site.52ef21.js',
	);
	return ! empty( $assets[ $asset ] ) ? $assets[ $asset ] : false;
}
